security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # Désactivation temporaire de LDAP
        # ldap_user_provider:
        #     id: App\Security\LdapUserProvider
        
        # Utilisation d'un provider en mémoire temporaire
        in_memory:
            memory:
                users:
                    admin: { password: '$2y$13$TYRJRRmH.QOvDQcBdJxYsOQI.ORhxZ.VQmGDzJnGCc1UpBcKUPBJO', roles: ['ROLE_ADMIN'] } # mot de passe: admin
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: in_memory
            # custom_authenticator: App\Security\LdapAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        # Commenté temporairement pour les tests
        # - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
