security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        ldap_user_provider:
            id: App\Security\LdapUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: ldap_user_provider
            custom_authenticator: App\Security\LdapAuthenticator
            entry_point: App\Security\LdapAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/lines, roles: ROLE_VISITEUR_LIGNES }
        - { path: ^/equipment, roles: ROLE_VISITEUR_PARC }
        - { path: ^/boxes, roles: ROLE_VISITEUR_BOXS }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_MODIFIEUR
            - ROLE_VISITEUR_TOUT
            - ROLE_VISITEUR_LIGNES
            - ROLE_VISITEUR_PARC
            - ROLE_VISITEUR_BOXS
        ROLE_MODIFIEUR:
            - ROLE_VISITEUR_TOUT
            - ROLE_VISITEUR_LIGNES
            - ROLE_VISITEUR_PARC
            - ROLE_VISITEUR_BOXS
        ROLE_VISITEUR_TOUT:
            - ROLE_VISITEUR_LIGNES
            - ROLE_VISITEUR_PARC
            - ROLE_VISITEUR_BOXS

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
