version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: sru_app
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    restart: unless-stopped
    networks:
      sru_network:
        ipv4_address: 172.40.0.10

  webserver:
    image: httpd:2.4
    container_name: sru_webserver
    ports:
      - "4080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
      sru_network:
        ipv4_address: 172.40.0.11

  pgadmin:
    image: dpage/pgadmin4
    container_name: sru_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "4081:80"
      - "4044:443"
    depends_on:
      - database
    restart: unless-stopped
    networks:
      sru_network:
        ipv4_address: 172.40.0.3

  database:
    image: postgres:16
    container_name: sru_postgresql16
    environment:
      POSTGRES_DB: agglo34_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:4032"
    restart: unless-stopped
    networks:
      sru_network:
        ipv4_address: 172.40.0.2
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "agglo34_db", "-U", "admin"] 
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  sru_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

volumes:
  postgres_data:
  pgadmin_data:
